version: '3'
# Other docker-compose examples in /examples

services:
  minecraft-tekkit:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - "mc-tekkit:/data"
    environment:
      EULA: "TRUE"
      INIT_MEM: "4G"
      MAX_MEM: "8G"
    restart: always
    labels:
      - "--noconsole"
    networks:
      - www

networks:
  www:
    external:
      name: www

volumes:
  mc-tekkit: {}
